name: JSR Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish package
        run: npx jsr publish --allow-slow-types
